

def exception_handler(error):
    return f'error'
